config/routes.rb
Project::Application.routes.draw do
  resources :conferences
  
  resources :academic_titles

  resources :protocol_templates

  resources :dictionaries

  resources :degrees

  resources :emails

  resources :auditories

  resources :posts

  resources :participans

  resources :themes

  resources :protocols

  resources :employees

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout
  
  match 'get_number' => 'protocols#get_number'

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  
  resources :versions do 
    member { get 'revert' }
  end
  
  resources :protocols do
    member do
      get 'set_sign'   
      get 'versions'         
    end
    collection do
      post 'set_template'
      post 'change_view'
    end    
  end

  resources :users do
    collection { post 'update_roles' }
  end

  resources :protocol do
    collection do     
      get 'set_sign'      
    end    
  end
  
  resources :employees do
    member do
      get 'delete'      
    end
  end    
  
  root :to => "protocols#index"

end

app/models/academic_title.rb
class AcademicTitle < ActiveRecord::Base
	has_many :employees
end

app/controllers/academic_titles_controller.rb
class AcademicTitlesController < ApplicationController
  # GET /academic_titles
  # GET /academic_titles.json
  def index
    @academic_titles = AcademicTitle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @academic_titles }
    end
  end

  # GET /academic_titles/1
  # GET /academic_titles/1.json
  def show
    @academic_title = AcademicTitle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @academic_title }
    end
  end

  # GET /academic_titles/new
  # GET /academic_titles/new.json
  def new
    @academic_title = AcademicTitle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @academic_title }
    end
  end

  # GET /academic_titles/1/edit
  def edit
    @academic_title = AcademicTitle.find(params[:id])
  end

  # POST /academic_titles
  # POST /academic_titles.json
  def create
    @academic_title = AcademicTitle.new(params[:academic_title])

    respond_to do |format|
      if @academic_title.save
        format.html { redirect_to @academic_title, :notice => 'Academic title was successfully created.' }
        format.json { render :json => @academic_title, :status => :created, :location => @academic_title }
      else
        format.html { render :action => "new" }
        format.json { render :json => @academic_title.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /academic_titles/1
  # PUT /academic_titles/1.json
  def update
    @academic_title = AcademicTitle.find(params[:id])

    respond_to do |format|
      if @academic_title.update_attributes(params[:academic_title])
        format.html { redirect_to @academic_title, :notice => 'Academic title was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @academic_title.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /academic_titles/1
  # DELETE /academic_titles/1.json
  def destroy
    @academic_title = AcademicTitle.find(params[:id])
    @academic_title.destroy

    respond_to do |format|
      format.html { redirect_to academic_titles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/academic_titles_helper.rb
module AcademicTitlesHelper
end

app/views/academic_titles/_form.html.haml
= form_for @academic_title do |f|
  =render "errors/error", :obj => @academic_title

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :short_name
    = f.text_field :short_name
  .actions
    = f.submit 'Save'

app/views/academic_titles/edit.html.haml
%h1 Editing academic_title

= render 'form'

= link_to 'Show', @academic_title
\|
= link_to 'Back', academic_titles_path

app/views/academic_titles/index.html.haml
%h1 Listing academic_titles

%table
  %tr
    %th Name
    %th Short name
    %th
    %th
    %th

  - @academic_titles.each do |academic_title|
    %tr
      %td= academic_title.name
      %td= academic_title.short_name
      %td= link_to 'Show', academic_title
      %td= link_to 'Edit', edit_academic_title_path(academic_title)
      %td= link_to 'Destroy', academic_title, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Academic title', new_academic_title_path

app/views/academic_titles/new.html.haml
%h1 New academic_title

= render 'form'

= link_to 'Back', academic_titles_path

app/views/academic_titles/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @academic_title.name
%p
  %b Short name:
  = @academic_title.short_name

= link_to 'Edit', edit_academic_title_path(@academic_title)
\|
= link_to 'Back', academic_titles_path