config/routes.rb
Project::Application.routes.draw do
  resources :conferences
  
  resources :academic_titles

  resources :protocol_templates

  resources :dictionaries

  resources :degrees

  resources :emails

  resources :auditories

  resources :posts

  resources :participans

  resources :themes

  resources :protocols

  resources :employees

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout
  
  match 'get_number' => 'protocols#get_number'

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  
  resources :versions do 
    member { get 'revert' }
  end
  
  resources :protocols do
    member do
      get 'set_sign'   
      get 'versions'         
    end
    collection do
      post 'set_template'
      post 'change_view'
    end    
  end

  resources :users do
    collection { post 'update_roles' }
  end

  resources :protocol do
    collection do     
      get 'set_sign'      
    end    
  end
  
  resources :employees do
    member do
      get 'delete'      
    end
  end    
  
  root :to => "protocols#index"

end

app/models/employee.rb
# coding: utf-8

class Employee < ActiveRecord::Base
	scope :full_load, includes(:post, :degrees, :academic_title)
  
	belongs_to :post
	belongs_to :academic_title
	belongs_to :user, :dependent => :destroy
	has_many :participants
	has_many :themes, :through => :participants
	has_and_belongs_to_many :protocols
	has_and_belongs_to_many :degrees	  		  

  attr_reader :employee_degree_ids

  validates :f, :presence => true,
                :length => { :within => 2..30 },
                :format => /^[A-Z,А-Я]{1}[a-z,а-я]{2,30}$/i
                
  validates :i, :presence => true,
                :length => { :within => 2..30 },
                :format => /^[A-Z,А-Я]{1}[a-z,а-я]{2,30}$/i
                
  validates :o, :presence => true,
                :length => { :within => 2..30 },
                :format => /^[A-Z,А-Я]{1}[a-z,а-я]{2,30}$/i  
  
  def fio
      "#{i.first}. #{o.first}. #{f}"    
  end    
  
  def long_fio
      "#{f} #{i} #{o}"
  end    
  
  def degree?(id)
     self.degrees.exists?(id)    
  end
  
  def get_info
  	info = []
  	if !post.nil?
  		pname = post.short_name
  		pname += '.' if pname[-1] != 46 # '.'
  		info << pname
  	end
  	if !academic_title.nil?
  		ac_title = academic_title.short_name
  		ac_title += '.' if ac_title[-1] != 46 # '.'
  		info << ac_title
  	end
  	degrees = show_degrees
  	info << show_degrees if !degrees.empty?
  	info.join(", ")
  end
  
  def show_degrees
  	tmp = []
  	self.degrees.each do|degree|
  		dname = degree.name
  		dname += '.' if dname[-1] != 46 # '.'
  		tmp << dname
  	end
  	tmp.join(", ")
  end
  
  def employee_degree_ids=(ids)
    self.degree_ids = ids.reject(&:blank?)    
  end
end

app/controllers/employees_controller.rb
# coding: utf-8


class EmployeesController < ApplicationController
  before_filter :check_admin_user
  # GET /employees
  # GET /employees.json
  def index
    deleted = false
    if !params[:deleted].blank?       
      deleted = params[:deleted].to_i == 1 ? false : true
    end    
    @employees = Employee.where(:deleted => deleted).full_load
    
    respond_to do |format|
      format.html   	          			        
      format.json do
        q = params[:q]
        qup = q.mb_chars.downcase.to_s
        @employees= Employee.where("(f LIKE ? OR i LIKE ? OR o LIKE ?)",
        "%#{qup}%", "%#{qup}%", "%#{qup}%").all
        render :json=>@employees.map(&:attributes)
      end
      format.js { render :layout => false }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.full_load.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.full_load.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, :notice => 'Сотрудник добавлен' }
        format.json { render :json => @employee, :status => :created, :location => @employee }
      else
        format.html { render :action => "new" }
        format.json { render :json => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.full_load.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, :notice => 'Сотрудник сохранен' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @employee.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def delete  
  	employee = Employee.find(params[:id])
  	msg = ""
  	if employee.deleted
  		msg = "Сотрудник уже удален"
  	else
  	  	employee.deleted = true
  		employee.users.delete_all
  		employee.save
  		msg = "Сотрудник и все его аккаунты удалены"
  	end
  	redirect_to employees_path, :notice => msg
  end
  
  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :ok }
    end
  end
end

app/helpers/employees_helper.rb
# coding: utf-8

module EmployeesHelper
 	def get_posts
		%w("секретарь председатель преподаватель")
	end
	def show_posts(employee)
		options = "<option value = #{nil}>Выберите должность</option>"		
		Post.all.map do |p|
		 if p.id == employee.post_id  
		   options += "<option selected value = #{p.id}>#{p.name}</option>"
		   next
		 end
	        options += "<option value = #{p.id}>#{p.name}</option>"       
		end
		options.html_safe
	end
	
	def show_academic_title(employee)
		options = "<option value = #{nil}>Выберите звание</option>"		
		AcademicTitle.all.map do |ac|
		 if ac.id == employee.academic_title_id
		 	options += "<option selected value = #{ac.id}>#{ac.name}</option>"
		 	next
		 end
		 options += "<option value = #{ac.id}>#{ac.name}</option>"
		end
		options.html_safe
	end
end

app/views/employees/_employees.html.haml
%table{:class => "table table-bordered table-striped"}
  %tr
    %th ФИО
    %th Должность
    %th Ученое звание
    %th Ученые степени    
    %th{:colspan => 2} Действия

  - @employees.each do |employee|
    %tr
      %td= employee.long_fio
      %td= employee.post.name if !employee.post.nil?
      %td= employee.academic_title.name if !employee.academic_title.nil?      
      %td= employee.show_degrees
      %td=link_to 'Редактировать', edit_employee_path(employee), :class => "btn btn-success"
      -if not employee.deleted
        %td=link_to 'Заблокировать доступ', delete_employee_path(employee), :confirm => 'Вы уверены?', :class => "btn btn-danger"

app/views/employees/_form.html.haml
= form_for @employee, :class => "edit-form" do |f|
  =render "errors/error", :obj => @employee
  .field
    = f.label :f
    = f.text_field :f
  .field
    = f.label :i
    = f.text_field :i
  .field
    = f.label :o
    = f.text_field :o
  .field
    = f.label :post_id
    = f.select :post_id, show_posts(@employee)
  .field
    = f.label :academic_title_id
    = f.select :academic_title_id, show_academic_title(@employee)
  .field      
    =f.label :employee_degree_ids
    %ul
      -Degree.find_each do |d|
        -id = d.id
        %li
          =f.check_box :employee_degree_ids, {:multiple => true, :checked => f.object.degree?(id)}, id, nil 
          =d.name
  .actions
    = f.submit 'Сохранить', :class => "btn"

app/views/employees/edit.html.haml
%h3 Редактирование сотрудника

= link_to 'Показать', @employee, :class => "btn btn-primary"
\|
= link_to 'Назад', employees_path,  :class => "btn btn-primary"

= render 'form'

app/views/employees/index.html.haml
:javascript
  $(function(){
    $("#deleted").change(function() {                        
      var value = 1;
      if ($(this).attr("checked")) value = 0;
      $.get("#{employees_path}", {"deleted" : value }, null, "script");
      return false;
    });
  });
%h3 Состав кафедры
%br
=link_to 'Новый сотрудник', new_employee_path, :class => "btn btn-primary"
%br
Удаленные
=check_box_tag "deleted", 1, params[:deleted].blank? ? false : true
#employees
  =render 'employees'
     

app/views/employees/index.js.erb
$("#employees").html("<%= escape_javascript(render("employees")) %>");

app/views/employees/new.html.haml
%h3 Новый сотрудник

= render 'form'

= link_to 'Назад', employees_path, :class => "btn btn-success"

app/views/employees/show.html.haml
%p#notice= notice

%p
  %b ФИО:
  = @employee.long_fio  
%p
  %b Должность:
  = @employee.post_id != nil ? @employee.post.name : "нет"
%p  
  %b Ученые степени:
  = @employee.show_degrees
%p
  %b Ученое звание:
  = @employee.academic_title_id != nil ? @employee.academic_title.name : "нет"

  
= link_to 'Редактировать', edit_employee_path(@employee), :class => "btn btn-success"
\|
= link_to 'Назад', employees_path, :class => "btn btn-success"