config/routes.rb
Project::Application.routes.draw do
  resources :conferences
  
  resources :academic_titles

  resources :protocol_templates

  resources :dictionaries

  resources :degrees

  resources :emails

  resources :auditories

  resources :posts

  resources :participans

  resources :themes

  resources :protocols

  resources :employees

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout
  
  match 'get_number' => 'protocols#get_number'

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  
  resources :versions do 
    member { get 'revert' }
  end
  
  resources :protocols do
    member do
      get 'set_sign'   
      get 'versions'         
    end
    collection do
      post 'set_template'
      post 'change_view'
    end    
  end

  resources :users do
    collection { post 'update_roles' }
  end

  resources :protocol do
    collection do     
      get 'set_sign'      
    end    
  end
  
  resources :employees do
    member do
      get 'delete'      
    end
  end    
  
  root :to => "protocols#index"

end

app/models/protocol_template.rb
class ProtocolTemplate < ActiveRecord::Base
    has_paper_trail
    has_many :protocols, :order => "protocols.date DESC"
    validates :name, :presence => true, :uniqueness => true, :length => { :within => 3..50 }
    validates :body, :presence => true
    
    def self.check_html(str)
	    str.gsub('<li>', "\\item ").
    		   gsub("<ul>", "\\begin{itemize}").
    		   gsub("<ol>", "\\begin{enumerate}").
    		   gsub("</ul>", "\\end{itemize}").
    		   gsub("</ol>", "\\end{enumerate}").
     	   gsub('<b>', "\\textbf{").
     	   gsub('</b>', "}")
    end
end

app/controllers/protocol_templates_controller.rb
# coding: utf-8

class ProtocolTemplatesController < ApplicationController
  before_filter :check_regular_user
  before_filter :check_secretary_user
  # GET /protocol_templates
  # GET /protocol_templates.json
  def index
    @protocol_templates = ProtocolTemplate.all
    @protocols = []
    if !params[:tid].blank?    
	    @protocols = Protocol.where(:protocol_template_id =>
	                                 params[:tid]).order("date DESC")
	    @protocols = @protocols.page(params[:page]).per(10)
	    auds = Auditory.joins("INNER JOIN protocols ON protocols.id = auditories.id")
	    @auditories, @templates = {}, {}
	    templates = ProtocolTemplate.joins("INNER JOIN protocols ON 	protocols.protocol_template_id = protocol_templates.id")    
	    auds.each {|a| @auditories[a.id] = a.number }
	    templates.each {|t| @templates[t.id] = t.name }        
    end
    respond_to do |format|
      format.html # index.html.erb
      format.js { render :layout => false }
      format.json { render :json => @protocol_templates }
    end
  end

  # GET /protocol_templates/1
  # GET /protocol_templates/1.json
  def show    
    if Protocol.count == 0
		redirect_to protocol_templates_path, :notice => "Не найдено протоколов для просмотра"
    else
		@protocol_template = ProtocolTemplate.find(params[:id])    
		@protocol = Protocol.first
		@protocol_themes = @protocol.themes    
		@chairman = @protocol.chairman.fio    
		@head_of_depart = Employee.first.fio
		@employees = @protocol.get_employees
		@secretary = @protocol.secretary.fio 
		@date = @protocol.date.strftime("%d.%m.%y")    
		@body = ERB.new(@protocol_template.body).result(binding)
		respond_to do |format|		
			format.pdf
			format.html
		end
	end
  end

  # GET /protocol_templates/new
  # GET /protocol_templates/new.json
  def new
    @protocol_template = ProtocolTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @protocol_template }
    end
  end

  # GET /protocol_templates/1/edit
  def edit    
    @protocol_template = ProtocolTemplate.find(params[:id])
    flash[:notice] = "Элементы кода, расположенные между <% и %> изменять не желательно!"
  end

  # POST /protocol_templates
  # POST /protocol_templates.json
  def create
    @protocol_template = ProtocolTemplate.new(params[:protocol_template])

    respond_to do |format|
      if @protocol_template.save
        format.html { redirect_to @protocol_template, :notice => 'Шаблон создан.' }
        format.json { render :json => @protocol_template, :status => :created, :location => @protocol_template }
      else
        format.html { render :action => "new" }
        format.json { render :json => @protocol_template.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /protocol_templates/1
  # PUT /protocol_templates/1.json
  def update
    @protocol_template = ProtocolTemplate.find(params[:id])

    respond_to do |format|
      if @protocol_template.update_attributes(params[:protocol_template])
        format.html { redirect_to @protocol_template, :notice => "Шаблон изменен #{undo_link}." }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @protocol_template.errors, :status => :unprocessable_entity }
      end
    end
  end
  private

  def undo_link
    view_context.link_to("Отменить последние изменения", revert_version_path(@protocol_template.versions.scoped.last), :method => :post)
  end
end

app/helpers/protocol_templates_helper.rb
# coding:utf-8
module ProtocolTemplatesHelper
     # загрузить учебные года для шаблона
	def load_years(year)
	    options = "<option value = '-1'>Не выбрано</option>"
	    years = Protocol.get_academic_years.reverse
   	    last_year = years.last + 1
    	    # плюс 5 лет
	    5.times { |x| years << last_year + x }
	    years.each do |ac|    	      	      
	        if ac == year
      	      options += "<option selected value = #{ac}>#{ac}</option>"
             else     	 
      	      options += "<option value = #{ac}>#{ac}</option>"     	 
     	   end
	    end  	    
	    options.html_safe	    
     end
end

app/views/protocol_templates/_form.html.haml
= form_for @protocol_template do |f|
  =render "errors/error", :obj => @protocol_template
  .actions
    = f.submit :class => "btn"
  .field
    = f.label :name
    %br
    = f.text_field :name
  .field
    = f.label :body
    %br
    = f.text_area :body, :style => "width: 50%;", :rows => 60

app/views/protocol_templates/edit.html.haml
%h3 Редактирование шаблона
= link_to 'Показать', @protocol_template, :class => "btn btn-success"
\|
= link_to 'Назад', protocol_templates_path, :class => "btn btn-success"

= render 'form'

app/views/protocol_templates/index.html.haml
:javascript
  $(function(){
    $("#select_template").live("click", function() {
      var tid = $(this).attr("data_id");          
      $("#protocols").html("#{escape_javascript(image_tag('/images/loader.gif'))}");
      $.get("#{protocol_templates_path}", {"tid" : tid}, null, "script");      
      return false;
    });
  });
  $("#protocols div.pagination a").live("click", function(){
      $("#protocols").html("#{escape_javascript(image_tag('/images/loader.gif'))}");            
      $.getScript(this.href);
      return false;
  });
  $("#datepicker2").datepicker();
-if @protocol_templates.count == 0
  Шаблонов нет
-else
  =form_tag set_template_protocols_path, :style => "width: 98%" do
    %h3 Шаблоны протоколов
    %table{:class => "table table-bordered table-striped"}
      %tr
        %th Название шаблона
        %th{:colspan => 2} Действия
        %th Установить для протоколов
        %th Протоколы    
      - @protocol_templates.each do |protocol_template|
        %tr
          %td= protocol_template.name
          %td= link_to 'Посмотреть в PDF', protocol_template_path(protocol_template, :format => :pdf), :class => "btn btn-success"
          %td= link_to 'Редактировать', edit_protocol_template_path(protocol_template), :class => "btn btn-success"        
          %td
            С            
            = select_tag "dates[#{protocol_template.id}][from]", load_years(protocol_template.apply_from)
            %br
            По
            = select_tag "dates[#{protocol_template.id}][to]", load_years(protocol_template.apply_to)
             
          %td=link_to 'Показать', "#", :data_id => protocol_template.id, :id => "select_template", :class => "btn btn-success"
    %br
    =submit_tag 'Сохранить', :class => "btn"
%br
#protocols
-if @protocols.size != 0
  =render 'protocols/view_types/list', :protocols => @protocols
%br
= link_to 'Новый шаблон', new_protocol_template_path, :class => "btn btn-primary"

app/views/protocol_templates/index.js.erb
$("#protocols").html("<%= escape_javascript(render("/protocols/view_types/list", :protocols => @protocols)) %>");

app/views/protocol_templates/new.html.haml
%h3 Новый шаблон
= link_to 'Назад', protocol_templates_path, :class => "btn btn-success"

= render 'form'

app/views/protocol_templates/show.html.haml
= link_to 'Редактировать', edit_protocol_template_path(@protocol_template), :class => "btn btn-success"
\|
= link_to 'Назад', protocol_templates_path, :class => "btn btn-success"
\|
= link_to 'Посмотреть', protocol_template_path(@protocol_teamplate, :format => :pdf), :class => "btn btn-success"

%p  
  %br
  %b Шаблон:
  %br
  = text_area_tag "body", @body, :readonly => true, :style => "width: 50%;", :rows => 60

app/views/protocol_templates/show.pdf.erb
<%= raw(ProtocolTemplate.check_html(@body)) %>