config/routes.rb
Project::Application.routes.draw do
  resources :conferences
  
  resources :academic_titles

  resources :protocol_templates

  resources :dictionaries

  resources :degrees

  resources :emails

  resources :auditories

  resources :posts

  resources :participans

  resources :themes

  resources :protocols

  resources :employees

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout
  
  match 'get_number' => 'protocols#get_number'

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil
  
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"
  
  resources :versions do 
    member { get 'revert' }
  end
  
  resources :protocols do
    member do
      get 'set_sign'   
      get 'versions'         
    end
    collection do
      post 'set_template'
      post 'change_view'
    end    
  end

  resources :users do
    collection { post 'update_roles' }
  end

  resources :protocol do
    collection do     
      get 'set_sign'      
    end    
  end
  
  resources :employees do
    member do
      get 'delete'      
    end
  end    
  
  root :to => "protocols#index"

end

app/views/layouts/application.html.haml
-# coding: utf-8
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "Протоколы заседаний кафедры информационные системы и технологии"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag 'allcss/application', :media => "all"
    = javascript_include_tag 'alljs/application'
    :javascript
      $('.dropdown-toggle').dropdown();
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body{:style => "background-color: white;"}
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.i-bar
            %span.i-bar
            %span.i-bar
          
            %a.brand{:href => "#"}        
            %br    
            -if @current_user and @current_user.employee                         
              %ul.nav.pull-right  
                %li.dropdown#menu1
                  =link_to @current_user.employee.long_fio + '▼', '#', :class => "dropdown-toggle", :"data-toggle" =>"dropdown"
                  %ul.dropdown-menu    
                    -#%li=link_to "Личный кабинет", edit_user_path(@current_user),:id=>"logout"              
                    %li=link_to "Выход", logout_path,:id=>"logout"                              
                         
          %ul.nav.nav-pills
            %li= link_to "Заседания", conferences_path
            %li= link_to "Протоколы", protocols_path            
            -if @current_user and @current_user.admin?
              %li= link_to "Состав кафедры", employees_path
              %li= link_to "Пользователи", users_path     

                         
    %br
    .container-fluid
      .row-fluid                         
         
        .span12       
          %br
          %br
          -unless notice.blank?
            .alert.alert-success
              %a{:class => "close", 'data-dismiss' => "alert"} &times;              
              = raw(notice)
          -unless flash[:error].blank?
            .alert.alert-error
              %a{:class => "close", 'data-dismiss' => "alert"} &times;
              = flash[:error]
        .hero-unit{:style => "background: white; margin: 0 auto; width: 90%;"}
          = yield          

    
      %footer
        %p &copy; МГИУ 2012
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster    

app/views/layouts/login.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "Протоколы заседаний кафедры информационные системы и технологии"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    = stylesheet_link_tag 'allcss/application', :media => "all"
    = javascript_include_tag 'alljs/application'
    
    :javascript
      $('.dropdown-toggle').dropdown();
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body{:style => "background-color: white;"}                             
    .container-fluid
      .row-fluid               
        .span12                
          -unless notice.blank?
            .alert.alert-success
              %a{:class => "close", 'data-dismiss' => "alert"} &times;
              = notice
          -unless flash[:error].blank?
            .alert.alert-error
              %a{:class => "close", 'data-dismiss' => "alert"} &times;
              = flash[:error]
        .hero-unit{:style => "background: white; margin: 0 auto; width: 90%;"}
          = yield          
         
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster    